### ISSUE TITLE
search-usernamepassword  fuction returns completed but no password 

### ISSUE THREAD

**Issue by jaishan** [Mr-Un1k0d3r/RedTeamPowershellScripts#1]
S C:\RedTeamPowershellScripts-master\scripts> Search-UserPassword -Username amd66
[*] amd66
[-] Property not found
[+] Process completed...

I tried in domain environment no output???

**Comment by Mr-Un1k0d3r** [comment]
This cmdlet is searching for the userPassword field in the Active Directory this field is NOT present by default. In this case the user "amd66" userPassword was probably never set. The userPassword used to be set by various 3rd party product such as Lotus Note.

**Comment by jaishan** [comment]
So what field i should use insted of userPassword??

**Comment by Mr-Un1k0d3r** [comment]
Not sure I understand what you are looking for... by default there is no such thing as clear text password stored in the AD.

**Comment by jaishan** [comment]
Probably i am not able to understand how exactly this script has to be executed? Is there any wiki or blog which describe its function in more detail.
